### ISSUE TITLE
Feature request: Multiline textbox (Textarea)

### ISSUE THREAD

**Issue by seanhakbb** [dawoe/umbraco-multilanguage-textbox#7]
Hi, appreciate your work and this feature is awesome compared to manually creating local specific fields in Umbraco Media.

However we feel the input type="text" a bit limiting, it would be nice if we could enable multiline (textarea) inside the data type settings.
This works better for longer alt texts on smaller screen (since text would jump to new line instead of being cropped) and we are also planning to use this property for video transcripts as well.

Let me know if you like the idea and fits this project scope and/or need help with a PR.

**Comment by dawoe** [comment]
Hi @seanhakbb 

This is now available in version 10.2, 12.1 and 13

In the datatype configuration you can choose if you want a text area
